pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                dir("kata") {
                    sh "mvn clean install"
                }
            }
        }

        stage('Test') {
            steps {
                dir("kata") {
                    sh "mvn test"
                }
            }
        }
    }
}